### ISSUE TITLE
globals.css Bug Report

### ISSUE THREAD

**Issue by Drihmia** [Drihmia/ACME-Education#14]
Here are the list of bugs I found in the code:

1. The CSS custom properties for the `--foreground-rgb` and `--background-start-rgb` variables in the dark mode media query are set to the same value (0, 0, 0), which means the text color and background color will be the same and may not be visible.
2. The `background` property for the `body` selector is missing a closing parenthesis, which will cause a syntax error.
3. The `linear-gradient` function for the `background` property of the `body` selector is missing a stop value for the first color, which will cause the gradient to start from transparent instead of the intended color.
4. The `iconify-icon` selector is missing a period before it, which means it will not select any elements.

Here's the corrected code:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 50, 50, 50;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      rgba(var(--background-start-rgb), 0),
      rgba(var(--background-end-rgb), 1)
    )
    rgb(var(--background-start-rgb));
}

@layer utilities {
  .text-balance {
    text-wrap: balance;
  }
}

.iconify-icon {
  display: inline-block;
  width: 1em;
  height: 1em;
}
```
